import type { ContactFormData, QuoteRequest } from '../types';

// Contact service for handling contact form submissions
export const contactService = {
  // Submit contact form
  async submitContactForm(data: ContactFormData): Promise<{ success: boolean; message: string }> {
    return new Promise((resolve) => {
      setTimeout(() => {
        // In production, this would send data to backend
        console.log('Contact form submitted:', data);
        resolve({
          success: true,
          message: 'Your message has been received. We will contact you shortly.'
        });
      }, 500);
    });
  },

  // Subscribe to newsletter
  async subscribeNewsletter(email: string): Promise<{ success: boolean; message: string }> {
    return new Promise((resolve) => {
      setTimeout(() => {
        console.log('Newsletter subscription:', email);
        resolve({
          success: true,
          message: 'Thank you for subscribing to our newsletter!'
        });
      }, 500);
    });
  },
};

// Quote service for handling quote requests
export const quoteService = {
  // Submit quote request
  async submitQuoteRequest(data: QuoteRequest): Promise<{ success: boolean; quoteId: string; message: string }> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const quoteId = `QUOTE-${Date.now()}`;
        console.log('Quote request submitted:', data);
        resolve({
          success: true,
          quoteId,
          message: 'Your quote request has been received. Check your email for details.'
        });
      }, 500);
    });
  },

  // Generate quote summary
  generateQuoteSummary(data: QuoteRequest): string {
    const items = data.products
      .map(p => `${p.productName} x${p.quantity}`)
      .join('\n');

    return `
QUOTATION SUMMARY
================
Quote ID: ${`QUOTE-${Date.now()}`}
Customer: ${data.fullName}
Company: ${data.companyName}
Email: ${data.email}
Phone: ${data.phoneNumber}
Location: ${data.projectLocation}

ITEMS:
${items}

TOTAL AMOUNT: $${data.totalAmount || 'To be calculated'}

NOTES: ${data.additionalNotes || 'None'}

---
Generated by Waan Afrika Water Solution
Complete Water Solutions for Africa
    `.trim();
  },
};

